app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
# app/home/views.py

from flask import abort, render_template,jsonify
from flask_login import current_user, login_required
from ..models import Noticia
from . import home

@home.route('/')
def homepage():
    """
    Render the homepage template on the / route
    """
    

    noticias = Noticia.query.all()
    return render_template('home/index.html', title="Home",noticias=noticias)


@home.route('/home')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    
    noticias = Noticia.query.all()
    return render_template('home/dashboard.html', title="Home", noticias=noticias)


# add admin dashboard view
@home.route('/admin/dashboard')
@login_required
def admin_dashboard():
    # prevent non-admins from accessing the page
    if not current_user.is_admin:
        abort(403)
   
    noticias = Noticia.query.all()
    return render_template('home/index.html', title="Home", noticias=noticias)

@home.route('/pag_noticia/<int:id>')
def pag_noticia(id):
    noticia = Noticia.query.get_or_404(id)
    return render_template('home/pag_noticia.html', title=noticia.titulo, noticia=noticia)

app/templates/home/admin_dashboard.html
{% extends "base.html" %}
{% block title %}Admin Dashboard{% endblock %}
{% block body %}

    <div class="container">
         {% for i in noticias %}
            <li class="link">
                <a href="{{ url_for('home.pag_noticia',id=i.id) }}">
                    <div class="{{i.titulo[:8].replace(' ','-')}}" >
                        <div class="texto">
                            <h1>{{i.titulo}}</h1>
                        </div>
                    </div>
                
                     <style type="text/css">
                        .{{i.titulo[:8].replace(' ','-')}}{
                            width: 500px;
                            height: 300px;
                            background-image: url("{{i.caminho_imagem}}");
                            background-repeat: no-repeat;
                            background-size: 500px 300px;
                            font-size: 15px;
                            margin: 0 auto;
                            padding-top: 200px;
                        }
                    </style>
                </a>
            </li>
        {% endfor%}
    </div>

{% endblock %}

app/templates/home/dashboard.html
<!-- app/templates/home/dashboard.html -->

{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
    <div class="container">
        {% for i in noticias %}
            <li class="link">
                <a href="{{ url_for('home.pag_noticia',id=i.id) }}">
                    <div class="{{i.titulo[:8].replace(' ','-')}}" >
                        <div class="texto">
                            <h1>{{i.titulo}}</h1>
                        </div>
                    </div>
                
                     <style type="text/css">
                        .{{i.titulo[:8].replace(' ','-')}}{
                            width: 500px;
                            height: 300px;
                            background-image: url("{{i.caminho_imagem}}");
                            background-repeat: no-repeat;
                            background-size: 500px 300px;
                            font-size: 15px;
                            margin: 0 auto;
                            padding-top: 200px;
                        }
                    </style>
                </a>
            </li>
        {% endfor%}
    </div>

{% endblock %}

app/templates/home/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="container">
        {% for i in noticias %}
            <li class="link">
                <a href="{{ url_for('home.pag_noticia',id=i.id) }}">
                    <div class="{{i.titulo[:8].replace(' ','-')}}" >
                        <div class="texto">
                            <h1>{{i.titulo}}</h1>
                        </div>
                    </div>
                
                     <style type="text/css">
                        .{{i.titulo[:8].replace(' ','-')}}{
                            width: 500px;
                            height: 300px;
                            background-image: url("{{i.caminho_imagem}}");
                            background-repeat: no-repeat;
                            background-size: 500px 300px;
                            font-size: 15px;
                            margin: 0 auto;
                            padding-top: 200px;
                        }
                    </style>
                </a>
            </li>
        {% endfor%}

    </div>
{% endblock %}

app/templates/home/pag_noticia.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="container">
        <div class="noticia">
            <h1>{{noticia.titulo}}</h1>
            <img src="{{noticia.caminho_imagem}}">
            <p>{{noticia.texto}}</p>
        </div>
        <div class="limpa"></div>

</div>
{% endblock %}